# -*- coding: utf-8 -*-
"""
/***************************************************************************
 arpatest
                                 A QGIS plugin
 Plugin for testing ARPA API
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-12-29
        copyright            : (C) 2022 by Emanuele Capizzi
        email                : capizzi.emanuele@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load arpatest class from file arpatest.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .ARPA_test import arpatest
    return arpatest(iface)
