# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ARPAweather
                                 A QGIS plugin
 Simplifies the process of collecting and analyzing meteorological ground sensor data. The data are provided by the Environmental Protection Agency of Lombardia Region (ARPA Lombardia) in Northern Italy and include  comprehensive open datasets of weather observations collected over multiple years.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-02-14
        copyright            : (C) 2023 by Emanuele Capizzi - Politecnico di Milano
        email                : emanuele.capizzi@polimi.it
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ARPAweather class from file ARPAweather.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .arpaweather import ARPAweather
    return ARPAweather(iface)
